# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a887a677e406cc4fb4bf99d344cba064c896b375aea174dadd49789ac9fe96e3089a65f9c09567d36f5c4f044cc9dfcab2b99fb1f2fdcd1a69909323172cdb

test:
  secret_key_base: 12673eaa17c434a57b942d802d4c7f9713230fa9148e83912b9a3c28627cdbc320f9f1b9572d136a892befdf30f058359b81d6e77f82d72c7d49c8c06b6bae5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
